# "org" ensures this Service is used with the correct Serverless Framework Access Key
useDotenv: true

org: koeppster
service: box-event-webhook
plugins:
  - serverless-dotenv-plugin

# before you deploy your app, you should set credential with the follow cmd:
# serverless config credentials --provider aws --key $AWS_KEY$ --secret $AWS_SECRET$ -o
provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10 # server should still acknowledge Box skills engine within 10 seconds of receiving the event
  versionFunctions: true # maintains past versions in single deployment
  environment:
    box_client_id: ${env:BOX_CLIENT_ID}
    box_ciient_secret: ${env:BOX_CLIENT_SECRET}
    box_enterprise_id: ${env:BOX_ENTERPRISE_ID}
    mailer_host: ${env:MAILER_HOST}
    mailer_username: ${env:MAILER_USERNAME}
    mailer_password: ${env:MAILER_PASSWORD}
    mailer_sendto: ${env:MAILER_SENDTO}

# overwriting defaults
#  stage: ${opt:stage, 'dev'}
  region: us-east-1

# packaging information
package:
    exclude:
        - .gitignore
        - .git/**
    include:
      - static/**

functions:
  skill:
    handler: index.handler
    events: # The Events that trigger this Function
      - http:
          path: ${self:service}
          method: any
